services:
  authorization-api:
    build:
      context: ../backend/services/Authorization
      dockerfile: Dockerfile
    ports:
      - "5161:8080" 
    env_file:
      - ./.env  
    depends_on:
      - db  
    networks:
      - internal_network

  course-management-api:
    build:
      context: ../backend/services/CourseManagement
      dockerfile: Dockerfile
    ports:
      - "5181:8080" 
    env_file:
      - ./.env  
    depends_on:
      - db  
    networks:
      - internal_network

  db:
    build:
      context: ../database
      dockerfile: Dockerfile
    env_file:
      - ./.env
    networks:
      - internal_network

networks:
  internal_network:
    driver: bridge
