
services:
  authorization-api:
    build:
      context: ../backend/services/Authorization   # Point to the root of your backend folder
      dockerfile: Dockerfile  # Dockerfile for the Authorization service
    ports:
      - "5161:8080" 
    env_file:
      - ./.env  
    depends_on:
      - db  
    networks:
      - test

  course-management-api:
    build:
      context: ../backend/services/CourseManagement   # Point to the root of your backend folder
      dockerfile: Dockerfile  # Dockerfile for the Authorization service
    ports:
      - "5006:8080" 
    env_file:
      - ./.env  
    depends_on:
      - db  
    networks:
      - test

  # Example for a database container (if required)
  db:
    build:
      context: ../database   # Point to the root of your backend folder
      dockerfile: Dockerfile  # Dockerfile for the Authorization service
    # ports:
    #   - "5432:5432"  # Expose container port 80 to host machine port 5161
    env_file:
      - ./.env  # Load environment variables from the .env file
    networks:
      - test

volumes:
  db-data:

networks:
  test:
    driver: bridge
